import { CardItem } from "./types"

//Essa mockup foi usada para testes internos para design!

export const mockUpData:CardItem[] = [
  {
    id: 1,
    name: 'HQ1',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 2,
    name: 'HQ2',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 3,
    name: 'HQ3',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 4,
    name: 'HQ4',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 5,
    name: 'HQ1',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 6,
    name: 'HQ2',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 7,
    name: 'HQ3',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 8,
    name: 'HQ4',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 9,
    name: 'HQ1',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 10,
    name: 'HQ2',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 11,
    name: 'HQ3',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 12,
    name: 'HQ4',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 13,
    name: 'HQ1',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 14,
    name: 'HQ2',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 15,
    name: 'HQ3',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 16,
    name: 'HQ4',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
]

export const mockupData2:CardItem[] = [
  {
    id: 1,
    name: 'HQ1',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 2,
    name: 'HQ2',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 3,
    name: 'HQ3',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 4,
    name: 'HQ4',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 5,
    name: 'HQ1',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 6,
    name: 'HQ2',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 7,
    name: 'HQ3',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 8,
    name: 'HQ4',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 9,
    name: 'HQ1',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 10,
    name: 'HQ2',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 11,
    name: 'HQ3',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 12,
    name: 'HQ4',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 13,
    name: 'HQ1',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 14,
    name: 'HQ2',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 15,
    name: 'HQ3',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
  {
    id: 16,
    name: 'HQ4',
    price: 15.00,
    description: 'A brief description of the comic we are approaching!',
    quantity: 1,
  },
]